---
ansible_user: 'mds'
ansible_become_method: sudo
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_private_key_file: ~/.ssh/raspberrypi_key

# Github repos                                                                  
github_projects:                                                                
  - 'r4pi'                                                                      
  - 'r4pi-repo-conf'                                                            
  - 'usage_data'   
