---
ansible_user: 'mds'
ansible_become_method: sudo
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_private_key_file: ~/.ssh/raspberrypi_key

# fpm package creation tool version
fpm_version: '1.15.1'

# Github repos                                                                  
github_projects:                                                                
  - 'buildr'                                                                    
 
