---
ansible_user: 'mds'
ansible_become_method: sudo
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_private_key_file: ~/.ssh/raspberrypi_key

# fpm package creation tool version
fpm_version: '1.15.1'

# Github repos                                                                  
github_projects:
  - 'deb-repo'
  - 'r4pi'                                                                      
  - 'r4pi-repo-conf'                                                            
  - 'usage_data'   


# s3cfg config for s3cmd
access_key: "{{ vault_access_key }}"
gpg_passphrase: "{{ vault_gpg_passphrase }}"
secret_key: "{{ vault_secret_key }}"

