---
- name: Install common apt dependencies
  become: true
  apt:
    name:
      - git
      - htop
      - jq
      - mc
      - rsync
      - task-spooler
      - tree
      - unattended-upgrades
      - vim
    state: present
- name: Remove unwanted apt dependencies
  become: true
  apt:
    name:
      - weex
    state: absent
