---
- name: Check if R exists
  stat:
    path: /opt/R/release/bin/R
  register: r_check

- block:
    - name: Install system dependencies for R
      apt:
        name:
          - gfortran
          - libreadline-dev
          - libx11-dev
          - libxt-dev
          - libpng-dev
          - libjpeg-dev
          - libcairo2-dev
          - xvfb
          - libbz2-dev
          - libzstd-dev
          - libbrotli-dev
          - liblzma-dev
          - libssh-dev
          - libblas-dev
          - libopenblas-base
          - libopenblas-dev
          - liblapack-dev
          - liblapack3
          - libcurl4-openssl-dev
          - libssl-dev
          - libabsl-dev
          - libjemalloc-dev
          - zlib1g-dev
          - texinfo
          - texlive
          - texlive-fonts-extra
          - screen
          - gzip
          - wget
          - libpcre2-dev
          - openjdk-11-jdk
        state: present

    - name: Download R source
      unarchive:
        src: "https://cran.rstudio.com/src/base/R-{{ r_version\n
        | regex_search('^\\d', multiline=True)\n
        | trim }}/R-{{ r_version }}.tar.gz"
        remote_src: true
        dest: /usr/local/src
        creates: "/usr/local/src/R-{{ r_version }}"

    - name: Configure R compilation
      command:
        cmd: "./configure\n
              --prefix=/opt/R/release\n
              --enable-R-shlib\n
              --with-blas\n
              --with-lapack\n
              --enable-memory-profiling\n
              --with-tcltk\n
              --with-x"
        chdir: "/usr/local/src/R-{{ r_version }}"
        creates: "/usr/local/src/R-{{ r_version }}/Makeconf"

    - name: Compile R
      community.general.make:
        chdir: "/usr/local/src/R-{{ r_version }}"

    - name: Install R
      community.general.make:
        chdir: "/usr/local/src/R-{{ r_version }}"
        target: install

    - name: Remove installation files
      file:
        path: "/usr/local/src/R-{{ r_version }}"
        state: absent
  when: "r_check.stat.exists == false"
