---
- name: Install s3cmd
  become: true
  apt:
    name:
      - s3cmd
    state: present

- name: Install awscli for Debian
  become: true
  apt:
    name:
      - awscli
    state: present
  when: ansible_distribution == "Debian"

- name: install aws cli for Ubuntu
  become: true
  community.general.snap:
    name: aws-cli
    state: present
    classic: yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "noble"



- name: Apply .s3cfg
  ansible.builtin.template:
    src: s3cfg
    dest: "/home/{{ ansible_user }}/.s3cfg"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

