---
ansible_user: 'mds'
ansible_become_method: sudo
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_private_key_file: ~/.ssh/raspberrypi_key

# Rust toolchain version
rust_version: '1.67.1'

# Github repos                                                                  
github_projects:                                                                
  - 'pkg_builder'                                                               
 

# s3cfg config for s3cmd
access_key: "{{ vault_access_key }}"
gpg_passphrase: "{{ vault_gpg_passphrase }}"
secret_key: "{{ vault_secret_key }}"

