---
- name: Install R4Pi build primary
  hosts: buildprimary
  become: true

  pre_tasks:
    - name: Load dynamic variable files
      include_vars: "vars/architecture_vars_{{ ansible_architecture }}.yml"
      tags: always

    - name: Update packages
      import_role:
        name: update_packages
      tags: always

  tasks:
    - name: install additional packages
      apt:
        name:
          - "reprepro"
        state: present

    - name: Install AWS hosting tools
      import_role:
        name: aws_tools
      tags: always

    - name: Install git repos
      import_role:
        name: checkout_repos
      tags: always

    - name: Install fpm
      import_role:
        name: install_fpm
      tags: always

