---
- name: Install Basic Services and Configurations
  hosts: all
  become: true

  pre_tasks:
    - name: Load dynamic variable files
      include_vars: "vars/architecture_vars_{{ ansible_architecture }}.yml"
      tags: always

    - name: Update packages
      import_role:
        name: update_packages
      tags: always

  tasks:
    - name: Install common system dependencies
      apt:
        name:
          - htop
          - jq
          - task-spooler
          - tree
          - vim
          - weex
        state: present
    - name: configure the working environment
      import_role:
        name: configure_bash
      tags: always
