---
- name: Install Basic Services and Configurations
  hosts: buildberries
  become: true

  vars_files:
    - vars/config_vars.yml

  pre_tasks:
    - name: Load dynamic variable files
      include_vars: "vars/architecture_vars_{{ ansible_architecture }}.yml"
      tags: always

    - name: Update packages
      import_role:
        name: update_packages
      tags: always

  tasks:
    - name: Install common system dependencies
      apt:
        name:
          - cmake
          - gdal-bin
          - libarchive-dev
          - libcurl4-openssl-dev
          - libgdal-dev
          - libgeos-dev
          - libgit2-dev
          - libglpk-dev
          - libgmp-dev
          - libgmp3-dev
          - libgsl0-dev
          - libicu-dev
          - libjq-dev
          - libmagick++-dev
          - libmpfr-dev
          - libnode-dev
          - libopenmpi-dev
          - libpoppler-cpp-dev
          - libproj-dev
          - libprotobuf-dev
          - libsodium-dev
          - libsqlite3-dev
          - libudunits2-dev
          - libv8-dev
          - libxml2-dev
          - pandoc
          - protobuf-compiler
        state: present

    - name: Install Rust
      import_role:
        name: install_rust
      tags: rust
