---
- name: Install Basic Services and Configurations
  hosts: buildberries
  become: true

  vars_files:
    - vars/config_vars.yml

  pre_tasks:
    - name: Load dynamic variable files
      include_vars: "vars/architecture_vars_{{ ansible_architecture }}.yml"
      tags: always

    - name: Update packages
      import_role:
        name: update_packages
      tags: always

  tasks:
    - name: Install common system dependencies
      apt:
        name:
          - autoconf
          - automake
          - autopoint
          - autotools-dev
          - bison
          - cmake
          - debhelper
          - default-jdk
          - default-jdk-headless
          - default-jre
          - default-jre-headless
          - dh-autoreconf
          - dh-strip-nondeterminism
          - dwz
          - fonts-lmodern
          - gettext
          - gfortran
          - gir1.2-harfbuzz-0.0
          - intltool-debian
          - libarchive-zip-perl
          - libbison-dev
          - libblkid-dev
          - libbz2-dev
          - libcairo2-dev
          - libcairo-script-interpreter2
          - libcurl4-openssl-dev
          - libffi-dev
          - libfile-stripnondeterminism-perl
          - libfribidi-dev
          - libglib2.0-dev
          - libglib2.0-dev-bin
          - libgraphite2-dev
          - libharfbuzz-dev
          - libharfbuzz-gobject0
          - libjpeg-dev
          - libkpathsea6
          - liblapack-dev
          - liblzma-dev
          - liblzo2-2
          - libmime-charset-perl
          - libmount-dev
          - libopenblas-dev
          - libpango1.0-dev
          - libpcre2-dev
          - libpixman-1-dev
          - libpotrace0
          - libptexenc1
          - libreadline-dev
          - libselinux1-dev
          - libsepol1-dev
          - libsigsegv2
          - libsombok3
          - libssh-dev
          - libteckit0
          - libtexlua53
          - libtexluajit2
          - libtext-unidecode-perl
          - libtiff-dev
          - libtool
          - libunicode-linebreak-perl
          - libx11-dev
          - libxcb-render0-dev
          - libxcb-shm0-dev
          - libxext-dev
          - libxft-dev
          - libxml-libxml-perl
          - libxml-namespacesupport-perl
          - libxml-sax-base-perl
          - libxml-sax-perl
          - libxrender-dev
          - libxss-dev
          - libxt-dev
          - libxxhash0
          - libzzip-0-13
          - m4
          - mpack
          - openjdk-11-jdk
          - openjdk-11-jre
          - pango1.0-tools
          - po-debconf
          - preview-latex-style
          - t1utils
          - tcl8.6
          - tcl8.6-dev
          - tex-common
          - texinfo
          - texlive-base
          - texlive-binaries
          - texlive-extra-utils
          - texlive-fonts-extra
          - texlive-fonts-recommended
          - texlive-latex-base
          - texlive-latex-extra
          - texlive-latex-recommended
          - texlive-pictures
          - texlive-plain-generic
          - tk8.6
          - tk8.6-dev
          - x11proto-scrnsaver-dev
          - x11proto-xext-dev
          - xfonts-base
          - xfonts-encodings
          - xfonts-utils
          - xvfb
        state: present
