---
- name: Install Basic Services and Configurations
  hosts: buildberries
  become: true

  vars_files:
    - vars/config_vars.yml

  pre_tasks:
    - name: Load dynamic variable files
      include_vars: "vars/architecture_vars_{{ ansible_architecture }}.yml"
      tags: always

    - name: Update packages
      import_role:
        name: update_packages
      tags: always

  tasks:
    - name: Install common system dependencies
      apt:
        name:
          - awscli
          - htop
          - jq
          - s3cmd
          - task-spooler
          - tree
          - vim
          - weex
        state: present
