---
- name: Install R4Pi project specific tools and config
  hosts: buildprimary
  become: true

  vars_files:
    - vars/config_vars.yml

  pre_tasks:
    - name: Load dynamic variable files
      include_vars: "vars/architecture_vars_{{ ansible_architecture }}.yml"
      tags: always

    - name: Update packages
      import_role:
        name: update_packages
      tags: always

  tasks:
    - name: install additional packages
      apt:
        name:
          - "reprepro"
        state: present

    - name: Checkout git repos
      import_role:
        name: checkout_repos
      tags: r4pi
