---
- name: Install FPM deps ruby and rubygems
  apt:
    name:
      - ruby
      - rubygems
    state: present

- name: Install the fpm gem
  community.general.gem:
    name: fpm
    version: "{{ fpm_version }}"
    state: present
