---
# System Configurations ########################################################

# Security Configurations #####################################################

# Software Versions ###########################################################

# Rust toolchain version
rust_version: '1.67.1'
