---
- name: Install package build dependencies
  become: true
  apt:
    name:
      - cmake
      - gdal-bin
      - libarchive-dev
      - libcurl4-openssl-dev
      - libgdal-dev
      - libgeos-dev
      - libgit2-dev
      - libglpk-dev
      - libgmp-dev
      - libgmp3-dev
      - libgsl0-dev
      - libicu-dev
      - libjq-dev
      - libmagick++-dev
      - libmpfr-dev
      - libopenmpi-dev
      - libpoppler-cpp-dev
      - libproj-dev
      - libprotobuf-dev
      - libsodium-dev
      - libsqlite3-dev
      - libtbb-dev
      - libudunits2-dev
      - libv8-dev
      - libxml2-dev
      - pandoc
      - protobuf-compiler
    state: present

- name: Create symlink for R
  ansible.builtin.file:
    src: /opt/R/release/bin/R
    dest: /usr/bin/R
    owner: root
    group: root
    state: link
    force: yes

- name: Create symlink for Rscript
  ansible.builtin.file:
    src: /opt/R/release/bin/Rscript
    dest: /usr/bin/Rscript
    owner: root
    group: root
    state: link
    force: yes
