---
- name: Create the r4pi directory
  file:
    path: "/home/{{ ansible_user }}/r4pi"
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: git clone r4pi/pkg_builder
  become: false
  git:
    repo: "git@github.com:r4pi/pkg_builder.git"
    dest: "/home/{{ ansible_user }}/r4pi/packages"
    clone: yes
    update: yes

- name: git clone r4pi/buildr
  become: false
  git:
    repo: "git@github.com:r4pi/buildr.git"
    dest: "/home/{{ ansible_user }}/r4pi/buildr"
    clone: yes
    update: yes

