---
- name: Create the r4pi directory
  file:
    path: "/home/{{ ansible_user }}/r4pi"
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: git clone r4pi git repos
  become: false
  git:
    repo: "git@github.com:r4pi/{{ item }}.git"
    dest: "/home/{{ ansible_user }}/r4pi/{{ item }}"
    clone: yes
    update: yes
  with_items: "{{ github_projects }}"

