---
galaxy_info:
  role_name: apt_common
  author: R4Pi Team
  description: Common apt tools
  company: R4Pi.org
  license: MIT
  platforms:
    - name: RaspberryPiOS

  min_ansible_version: 2.10

dependencies: []
