---
- name: Install R build dependencies a-c
  become: true
  apt:
    name:
      - autoconf
      - automake
      - autopoint
      - autotools-dev
      - bison
      - cmake
    state: present
- name: Install R build dependencies d-f
  become: true
  apt:
    name:
      - debhelper
      - default-jdk
      - default-jdk-headless
      - default-jre
      - default-jre-headless
      - dh-autoreconf
      - dh-strip-nondeterminism
      - dwz
      - fonts-lmodern
    state: present
- name: Install R build dependencies g-i
  become: true
  apt:
    name:
      - gettext
      - gfortran
      - gir1.2-harfbuzz-0.0
      - intltool-debian
    state: present
- name: Install R build dependencies j-l
  become: true
  apt:
    name:
      - libarchive-zip-perl
      - libbison-dev
      - libblkid-dev
      - libbz2-dev
      - libcairo2-dev
      - libcairo-script-interpreter2
      - libcurl4-openssl-dev
      - libffi-dev
      - libfile-stripnondeterminism-perl
      - libfribidi-dev
      - libglib2.0-dev
      - libglib2.0-dev-bin
      - libgraphite2-dev
    state: present
- name: Install R build dependencies libh-libp
  become: true
  apt:
    name:
      - libharfbuzz-dev
      - libharfbuzz-gobject0
      - libjpeg-dev
      - libkpathsea6
      - liblapack-dev
      - liblzma-dev
      - liblzo2-2
      - libmime-charset-perl
      - libmount-dev
      - libopenblas-dev
      - libpango1.0-dev
      - libpcre2-dev
      - libpixman-1-dev
      - libpotrace0
      - libptexenc1
    state: present
- name: Install R build dependencies libr-libu
  become: true
  apt:
    name:
      - libreadline-dev
      - libselinux1-dev
      - libsigsegv2
      - libsombok3
      - libssh-dev
      - libteckit0
      - libtexlua53
      - libtext-unidecode-perl
      - libtiff-dev
      - libtool
      - libunicode-linebreak-perl
    state: present
- name: Install R build dependencies libv-libz
  become: true
  apt:
    name:
      - libx11-dev
      - libxcb-render0-dev
      - libxcb-shm0-dev
      - libxext-dev
      - libxft-dev
      - libxml-libxml-perl
      - libxml-namespacesupport-perl
      - libxml-sax-base-perl
      - libxml-sax-perl
      - libxrender-dev
      - libxss-dev
      - libxt-dev
      - libxxhash0
      - libzzip-0-13
    state: present
- name: Install R build dependencies m-p
  become: true
  apt:
    name:
      - m4
      - mpack
      - pango1.0-tools
      - po-debconf
      - preview-latex-style
    state: present
- name: Install R build dependencies q-t
  become: true
  apt:
    name:
      - t1utils
      - tcl8.6
      - tcl8.6-dev
      - tex-common
      - texinfo
      - texlive-base
      - texlive-binaries
      - texlive-extra-utils
      - texlive-fonts-recommended
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-latex-recommended
      - texlive-pictures
      - texlive-plain-generic
      - tk8.6
      - tk8.6-dev
    state: present
- name: Install R build dependencies t-z
  become: true
  apt:
    name:
      - x11proto-scrnsaver-dev
      - x11proto-xext-dev
      - xfonts-base
      - xfonts-encodings
      - xfonts-utils
      - xvfb
    state: present
- name: Install debian 11 specific dependencies
  become: true
  apt:
    name:
      - libsepol1-dev
    state: present
  when: ansible_distribution_version == "11"

- name: Install debian 12 specific dependencies
  become: true
  apt:
    name:
      - libsepol-dev
    state: present
  when: ansible_distribution_version == "12"

- name: Install Ubuntu 24.04 specific dependencies
  become: true
  apt:
    name:
      - libsepol-dev
    state: present
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "noble"
